name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '6.x'

    - name: Installing dependencies
      run: npm ci

    - name: Installing ESLint
      run: npm i -g eslint

    - name: Run ESLint
      run: eslint . --ext .ts

    - name: Installing Codecov
      run: npm i -g codecov

    - name: Installing devtools
      run: dev/install-zimtools.sh

    - name: Building code
      run: npm run build

    - name: Running tests (with Codecov)
      run: REDIS=redis://127.0.0.1:6379 ZIMCHECK_PATH=`find .. -name zimcheck` ZIMDUMP_PATH=`find .. -name zimdump` npm run codecov
      env:
        S3_URL: ${{ secrets.S3_URL }}

    - name: Upload Codecov stats
      uses: codecov/codecov-action@v3
      if: ${{ matrix.node-version == '18.x' }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
