name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '6.x'

    - name: Installing necessary packages
      run: sudo apt install gcc-9 g++-9 python3-pip libbz2-dev ccache zlib1g-dev uuid-dev

    - name: Installing dependencies
      run: npm ci

    - name: Installing Codecov
      run: npm i -g codecov

    - name: Installing devtools
      run: dev/install-zimtools.sh

    - name: Building code
      run: npm run build

    - name: Tunning tests (with Codecov)
      run: REDIS=redis://127.0.0.1:6379 ZIMCHECK_PATH=`find .. -name zimcheck` npm run codecov
      env:
        S3_URL: ${{ secrets.S3_URL }}

    - name: Tunning test
      run: npm run jest

    - name: Upload Codecov stats
      uses: codecov/codecov-action@v3
      if: ${{ matrix.node-version == '18.x' }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
